DROP TABLE IF EXISTS processed_events;
DROP TABLE IF EXISTS hashtags;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS videos;
DROP TEXT SEARCH CONFIGURATION IF EXISTS search_fr;
DROP FUNCTION IF EXISTS search_join(text[]);
DROP FUNCTION IF EXISTS search_fold(text);
